[workspace]
authors = ["Connor Stewart <connorstewarty@gmail.com>"]
channels = ["conda-forge"]
name = "pixi-package-management"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]

[feature.deps-slides.dependencies]
pandoc = "*"

[feature.tasks-slides.tasks]
build-slides = "pandoc -t revealjs -s -o index.html slides.md -V revealjs-url=https://unpkg.com/reveal.js"
clean-demo = "rm -rf cpp-greeter/.pixi cpp-greeter/pixi.lock cpp-greeter/pixi.toml"

[environments]
slides = ["deps-slides","tasks-slides"]
